config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  resources :drones do
    member do
      put 'take_off'
      put 'move'
      put 'stabilize'
      put 'land'
      put 'engine_break'
      put 'stop_drone'
      put 'tap_drone'
    end

    collection do
      get 'fly_drone'
    end
  end
  resources :engines
  resources :gyroscopes
  resources :orientation_sensors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drone.rb
class Drone < ApplicationRecord
  has_many :engines, dependent: :destroy
  has_one :gyroscope, dependent: :destroy
  has_one :orientation_sensor, dependent: :destroy

  validates :name, :colour, presence: true
end

app/models/engine.rb
class Engine < ApplicationRecord
  belongs_to :drone, optional: true

  validates :name, :power_indicator, presence: true
end

app/models/gyroscope.rb
class Gyroscope < ApplicationRecord
  belongs_to :drone, optional: true

  validates :name, presence: true
end

app/models/orientation_sensor.rb
class OrientationSensor < ApplicationRecord
  belongs_to :drone, optional: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  before_action :set_drone, only: [:show, :edit, :update, :destroy, :take_off,
                :move, :stabilize, :land, :engine_break, :stop_drone, :tap_drone]
  
  def index
    @drones = Drone.all
  end

  def show
  end

  def new
    @drone = Drone.new
  end
  
  def create
    @drone = Drone.new(drone_params)
      
    respond_to do |format|
     if @drone.save
        format.html { redirect_to drones_path, notice: 'Drone was successfully created.' }
     else
        format.html { render :new }
     end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
     if @drone.update(drone_params)
        format.html { redirect_to drones_path, notice: 'Drone was successfully updated.' }
     else
        format.html { render :edit, error: "#{@drone.errors.full_messages}" }
     end
    end
  end

  def destroy
    @drone.destroy

    respond_to do |format|
      format.html { redirect_to drones_path, notice: 'Drone was successfully deleted.' }
    end  
  end

  def fly_drone    
    @result = []

    Drone.all.each do |drone|
      @result << drone if drone.engines.present? && drone.gyroscope.present? && drone.orientation_sensor.present?
    end
    @result
  end

  def take_off
    @drone.update(status: 'on')
    @drone.engines.update_all(status: 'on')
    redirect_to drone_path(@drone), notice: "Drone has started ready to move....!"
  end
  
  def move
    @drone.update(status: 'moving')
    redirect_to drone_path(@drone), notice: "Drone is moving #{params[:direction]} side in the air"
  end

  def stabilize
    @drone.update(status: 'hovering')
    redirect_to drone_path(@drone), notice: "Drone is hovering in the air"
  end
  
  def land
    @drone.update(status: 'landed')
    redirect_to drone_path(@drone), notice: "Drone is landed safely"
  end

  def engine_break
    @drone.update(status: 'landed')
    @drone.engines.update_all(status: 'on')
    redirect_to drone_path(@drone), notice: "Drone will send a distress signal and start landing - LANDED"
  end

  def stop_drone
    @drone.update(status: 'off')
    @drone.engines.update_all(status: 'off')
    redirect_to fly_drone_drones_path, notice: "Drone fail to take off it sends a distress signal - DRONE STOPS"
  end
  
  def tap_drone
    redirect_to drone_path(@drone), notice: "Drone is tapped by hand it's hovering instead of crashing."
  end

  private

  def set_drone
    @drone = Drone.find(params[:id])
  end

  def drone_params
    params.require(:drone).permit(:name, :colour)
  end  
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]
  
  def index
    @engines = Engine.all
  end

  def show
  end

  def new
    @engine = Engine.new
  end
  
  def create
    @engine = Engine.new(engine_params)
      
    respond_to do |format|
     if @engine.save
        format.html { redirect_to engines_path, notice: 'Engine was successfully created.' }
     else
        format.html { render :new }
     end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
     if @engine.update(engine_params)
        format.html { redirect_to engines_path, notice: 'Engine was successfully updated.' }
     else
        format.html { render :edit, error: "#{@engine.errors.full_messages}" }
     end
    end
  end

  def destroy
    @engine.destroy

    respond_to do |format|
      format.html { redirect_to engines_path, notice: 'Engine was successfully deleted.' }
    end
  end

  private

  def set_engine
    @engine = Engine.find(params[:id])
  end

  def engine_params
    params.require(:engine).permit(:name, :power_indicator, :drone_id)
  end
end

app/controllers/gyroscopes_controller.rb
class GyroscopesController < ApplicationController
  before_action :set_gyroscope, only: [:show, :edit, :update, :destroy]
  
  def index
    @gyroscopes = Gyroscope.all
  end

  def show
  end

  def new
    @gyroscope = Gyroscope.new
  end
  
  def create
    @gyroscope = Gyroscope.new(gyroscope_params)
      
    respond_to do |format|
     if @gyroscope.save
        format.html { redirect_to gyroscopes_path, notice: 'Gyroscope was successfully created.' }
     else
        format.html { render :new }
     end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
     if @gyroscope.update(gyroscope_params)
        format.html { redirect_to gyroscopes_path, notice: 'Gyroscope was successfully updated.' }
     else
        format.html { render :edit, error: "#{@gyroscope.errors.full_messages}" }
     end
    end
  end

  def destroy
    @gyroscope.destroy

    respond_to do |format|
      format.html { redirect_to gyroscopes_path, notice: 'Gyroscope was successfully deleted.' }
    end
  end

  private

  def set_gyroscope
    @gyroscope = Gyroscope.find(params[:id])
  end

  def gyroscope_params
    params.require(:gyroscope).permit(:name, :x, :y, :z, :drone_id)
  end
end

app/controllers/orientation_sensors_controller.rb
class OrientationSensorsController < ApplicationController
  before_action :set_orientation_sensor, only: [:show, :edit, :update, :destroy]
  
  def index
    @orientation_sensors = OrientationSensor.all
  end

  def show
  end

  def new
    @orientation_sensor = OrientationSensor.new
  end
  
  def create
    @orientation_sensor = OrientationSensor.new(orientation_sensor_params)

    respond_to do |format|
      if @orientation_sensor.save
        format.html { redirect_to orientation_sensors_path, notice: 'OrientationSensor was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @orientation_sensor.update(orientation_sensor_params)
        format.html { redirect_to orientation_sensors_path, notice: 'OrientationSensor was successfully updated.' }
      else
        format.html { render :edit, error: "#{@orientation_sensor.errors.full_messages}" }
      end
    end
  end

  def destroy
    @orientation_sensor.destroy

    respond_to do |format|
      format.html { redirect_to orientation_sensors_path, notice: 'OrientationSensor was successfully deleted.' }
    end
  end

  private

  def set_orientation_sensor
    @orientation_sensor = OrientationSensor.find(params[:id])
  end

  def orientation_sensor_params
    params.require(:orientation_sensor).permit(:name, :pitch, :roll, :drone_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @drones_count = Drone.count
    @engines_count = Engine.count
    @gyroscopes_count = Gyroscope.count
    @orientation_sensors_count = OrientationSensor.count

    @result = []

    Drone.all.each do |drone|
      @result << drone if drone.engines.present? && drone.gyroscope.present? && drone.orientation_sensor.present?
    end
    @result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drones/_form.html.erb
<%= form_with model: @drone do |drone_form| %>
  <%= drone_form.label :name, "Name*" %>
  <%= drone_form.text_field :name, class: 'form-control', required: true %>

  <%= drone_form.label :colour, "Colour*" %>
  <%= drone_form.text_field :colour, class: 'form-control', required: true %>
  <br>
  <%= drone_form.submit params[:action] == 'new' ? "Create" : "Update", class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/drones/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/drones/fly_drone.html.erb
<div class="container">
  <div style="margin-top: 10px;margin-bottom: 10px;float: right;">
    <p> Ready To Fly Drones</p>
  </div>
  <table class="table table-sm" style='margin-top: 10px'>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Colour</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @result.present? %>
        <% @result.each do |drone| %>
          <tr>
            <td><%= drone.name %></td>
            <td><%= drone.colour %></td>
            <td><%= drone.created_at %></td>
            <td><%= drone.updated_at %></td>
            <td><%= drone.status %></td>
            <td>
              <%= link_to "View Drone", drone_path(drone), class: "btn btn-secondary btn-sm" %>
            </td>
          </tr>      
        <% end %>
      <% else %>
        <tr>
          <td>No Drones To Fly</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/drones/index.html.erb
<div class="container">
  <div style="margin-top: 10px;margin-bottom: 10px;float: right;">
    <a class="btn btn-secondary" href="/drones/new" role="button">New Drone</a>
  </div>
  <table class="table table-sm" style='margin-top: 10px'>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Colour</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @drones.present? %>
        <% @drones.each do |drone| %>
          <tr>
            <td><%= drone.name %></td>
            <td><%= drone.colour %></td>
            <td><%= drone.created_at %></td>
            <td><%= drone.updated_at %></td>
            <td><%= drone.status %></td>
            <td>
              <%= link_to "Edit", edit_drone_path(drone), class: "btn btn-secondary btn-sm" %>
              <%= link_to "Delete", drone_path(drone), method: 'delete', class: "btn btn-secondary btn-sm" %>
            </td>
          </tr>      
        <% end %>
      <% else %>
        <tr>
          <td>No Records Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/drones/new.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/drones/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-6' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <img src="/assets/drone.png" width="100%">

      <div class="bd-example">
        <% if @drone.status == "off" %>
          <%= link_to "TAKE OFF", take_off_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
        <% end %>
        <% if ["on", "moving", "hovering", "landed"].include? @drone.status  %>
          <%= link_to "STABILIZE", stabilize_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "LAND", land_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
          <p></p>
          <%= link_to "MOVE FORWARD", move_drone_path(@drone, direction: 'forward'), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "LEFT", move_drone_path(@drone, direction: 'left'), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "RIGHT", move_drone_path(@drone, direction: 'right'), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "BACK", move_drone_path(@drone, direction: 'back'), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "UP", move_drone_path(@drone, direction: 'up'), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "DOWN", move_drone_path(@drone, direction: 'down'), :method => :put, class: "btn btn-primary btn-sm" %>
          <p></p>
          <%= link_to "TAP DRONE", tap_drone_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "ENGINE BREAKS", engine_break_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
          <%= link_to "STOP DRONE", stop_drone_drone_path(@drone), :method => :put, class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>

    </div>
    <div class='col-md-6' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <p><b>Drone Details:</b></p>
      <span><b>Name:</b> <%= @drone.name %></span>
      <span><b>Colour:</b> <%= @drone.colour %></span>
      <span><b>Status:</b> <%= @drone.status %></span>
      <p></p>
      
      <p><b>Engine Details:</b></p>
      <table class="table table-sm" style='margin-top: 10px'>
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Power Indicator</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @drone.engines.each do |engine| %>
            <tr>
              <td><%= engine.name %></td>
              <td><%= engine.power_indicator %></td>
              <td><%= engine.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <p></p>
      <p><b>Gyroscope Details:</b></p>
      <span><b>Name:</b> <%= @drone.gyroscope.name %></span>
      <span><b>X-Vector:</b> <%= @drone.gyroscope.x %></span>
      <span><b>Y-Vector:</b> <%= @drone.gyroscope.y %></span>
      <span><b>Z-Vector:</b> <%= @drone.gyroscope.z %></span>

      <p></p>
      <p><b>Orientation Sensor Details:</b></p>
      <span><b>Name:</b> <%= @drone.orientation_sensor.name %></span>
      <span><b>Pitch:</b> <%= @drone.orientation_sensor.pitch %></span>
      <span><b>Roll:</b> <%= @drone.orientation_sensor.roll %></span>
    </div>
  </div>
</div>


<!-- <div class="container">
  <div class="bd-example">
    <button type="button" class="btn btn-primary">Primary</button>
    <button type="button" class="btn btn-secondary">Secondary</button>
    <button type="button" class="btn btn-success">Success</button>
    <button type="button" class="btn btn-danger">Danger</button>
    <button type="button" class="btn btn-warning">Warning</button>
    <button type="button" class="btn btn-info">Info</button>
    <button type="button" class="btn btn-light">Light</button>
    <button type="button" class="btn btn-dark">Dark</button>
    <button type="button" class="btn btn-link">Link</button>
  </div>
</div>
 -->

app/views/engines/_form.html.erb
<%= form_with model: @engine do |engine_form| %>
  <%= engine_form.label :name, "Name*" %>
  <%= engine_form.text_field :name, class: 'form-control', required: true %>

  <%= engine_form.label :power_indicator, "Power Indicator*" %>
  <%= engine_form.number_field :power_indicator, class: 'form-control', required: true %>

  <%= engine_form.label :drone_id, "Select Drone" %>
  <%= engine_form.collection_select :drone_id, Drone.order(:name), :id, :name, {include_blank: ''},   {class: 'form-control'} %>
  <br>
  <%= engine_form.submit params[:action] == 'new' ? "Create" : "Update", class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/engines/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/engines/index.html.erb
<div class="container">
  <div style="margin-top: 10px;margin-bottom: 10px;float: right;">
    <a class="btn btn-secondary" href="/engines/new" role="button">New Engine</a>
  </div>
  <table class="table table-sm" style='margin-top: 10px'>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Power Indicator</th>
        <th scope="col">Drone Name</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @engines.present? %>
        <% @engines.each do |engine| %>
          <tr>
            <td><%= engine.name %></td>
            <td><%= engine.power_indicator %></td>
            <td><%= engine.drone.name if engine.drone.present? %></td>
            <td><%= engine.created_at %></td>
            <td><%= engine.updated_at %></td>
            <td><%= engine.status %></td>
            <td>
              <%= link_to "Edit", edit_engine_path(engine), class: "btn btn-secondary btn-sm" %>
              <%= link_to "Delete", engine_path(engine), method: 'delete', class: "btn btn-secondary btn-sm" %>
            </td>
          </tr>      
        <% end %>
      <% else %>
        <tr>
          <td>No Records Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/engines/new.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/gyroscopes/_form.html.erb
<%= form_with model: @gyroscope do |gyroscope_form| %>
  <%= gyroscope_form.label :name, "Name*" %>
  <%= gyroscope_form.text_field :name, class: 'form-control', required: true %>

  <%= gyroscope_form.label :x, "X Vector*" %>
  <%= gyroscope_form.number_field :x, class: 'form-control', required: true %>

  <%= gyroscope_form.label :y, "Y Vector*" %>
  <%= gyroscope_form.number_field :y, class: 'form-control', required: true %>

  <%= gyroscope_form.label :z, "Z Vector*" %>
  <%= gyroscope_form.number_field :z, class: 'form-control', required: true %>

  <%= gyroscope_form.label :drone_id, "Select Drone" %>
  <%= gyroscope_form.collection_select :drone_id, Drone.order(:name), :id, :name, {include_blank: ''},   {class: 'form-control'} %>
  <br>
  <%= gyroscope_form.submit params[:action] == 'new' ? "Create" : "Update", class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/gyroscopes/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/gyroscopes/index.html.erb
<div class="container">
  <div style="margin-top: 10px;margin-bottom: 10px;float: right;">
    <a class="btn btn-secondary" href="/gyroscopes/new" role="button">New Gyroscope</a>
  </div>
  <table class="table table-sm" style='margin-top: 10px'>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">X-Vector</th>
        <th scope="col">Y-Vector</th>
        <th scope="col">Z-Vector</th>
        <th scope="col">Drone Name</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @gyroscopes.present? %>
        <% @gyroscopes.each do |gyroscope| %>
          <tr>
            <td><%= gyroscope.name %></td>
            <td><%= gyroscope.x %></td>
            <td><%= gyroscope.y %></td>
            <td><%= gyroscope.z %></td>
            <td><%= gyroscope.drone.name if gyroscope.drone.present? %></td>
            <td><%= gyroscope.created_at %></td>
            <td><%= gyroscope.updated_at %></td>
            <td>
              <%= link_to "Edit", edit_gyroscope_path(gyroscope), class: "btn btn-secondary btn-sm" %>
              <%= link_to "Delete", gyroscope_path(gyroscope), method: 'delete', class: "btn btn-secondary btn-sm" %>
            </td>
          </tr>      
        <% end %>
      <% else %>
        <tr>
          <td>No Records Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/gyroscopes/new.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DroneApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container-fluid">
      <%= render 'welcome/header' %>
      <% if flash[:notice].present? %>
        <div class="alert alert-success" style="text-align: center" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:error].present? %>
        <div class="alert alert-danger" style="text-align: center" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
      <div class="main-color" id="main-wrap">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/orientation_sensors/_form.html.erb
<%= form_with model: @orientation_sensor do |orientation_sensor_form| %>
  <%= orientation_sensor_form.label :name, "Name*" %>
  <%= orientation_sensor_form.text_field :name, class: 'form-control', required: true %>

  <%= orientation_sensor_form.label :pitch, "Pitch*" %>
  <%= orientation_sensor_form.select :pitch, [["X-AXIS", "X-AXIS"], ["Y-AXIS", "Y-AXIS"]], {}, {class: 'form-control'} %>

  <%= orientation_sensor_form.label :roll, "Roll*" %>
  <%= orientation_sensor_form.select :roll, [["X-AXIS", "X-AXIS"], ["Y-AXIS", "Y-AXIS"]], {}, {class: 'form-control'} %>

  <%= orientation_sensor_form.label :drone_id, "Select Drone" %>
  <%= orientation_sensor_form.collection_select :drone_id, Drone.order(:name), :id, :name, {include_blank: ''},   {class: 'form-control'} %>
  <br>
  <%= orientation_sensor_form.submit params[:action] == 'new' ? "Create" : "Update", class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/orientation_sensors/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/orientation_sensors/index.html.erb
<div class="container">
  <div style="margin-top: 10px;margin-bottom: 10px;float: right;">
    <a class="btn btn-secondary" href="/orientation_sensors/new" role="button">New Sensor</a>
  </div>
  <table class="table table-sm" style='margin-top: 10px'>
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Pitch</th>
        <th scope="col">Roll</th>
        <th scope="col">Drone Name</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @orientation_sensors.present? %>
        <% @orientation_sensors.each do |orientation_sensor| %>
          <tr>
            <td><%= orientation_sensor.name %></td>
            <td><%= orientation_sensor.pitch %></td>
            <td><%= orientation_sensor.roll %></td>
            <td><%= orientation_sensor.drone.name if orientation_sensor.drone.present? %></td>
            <td><%= orientation_sensor.created_at %></td>
            <td><%= orientation_sensor.updated_at %></td>
            <td>
              <%= link_to "Edit", edit_orientation_sensor_path(orientation_sensor), class: "btn btn-secondary btn-sm" %>
              <%= link_to "Delete", orientation_sensor_path(orientation_sensor), method: 'delete', class: "btn btn-secondary btn-sm" %>
            </td>
          </tr>      
        <% end %>
      <% else %>
        <tr>
          <td>No Records Found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orientation_sensors/new.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'></div>
    <div class='col-md-8' style="border: 1px solid #ccc;margin-top: 20px;padding: 10px">
      <%= render 'form' %>
    </div>
    <div class='col-md-2'></div>
  </div>
</div>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Drone Application</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/drones">Drones</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/engines">Engines</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gyroscopes">Gyroscopes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/orientation_sensors">Orientation Sensors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/drones/fly_drone">Ready To Fly Drones</a>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="container" style="margin-top: 50px">
  <h3>Welcome to Drone Application</h3>
  <p></p>
  <p></p>
  <p><b>Drones: </b><%= @drones_count %></p>
  <p><b>Engines: </b><%= @engines_count %></p>
  <p><b>Gyroscopes: </b><%= @gyroscopes_count %></p>
  <p><b>Orientation Sensors: </b><%= @orientation_sensors_count %></p>
  <p><b>Ready To Fly Drones: </b><%= @result.count %></p>
</div>